Repository BelfDev/uofg-msc-team-project, pull requests merged in 2020-02, with the labels that each got.

#16 Fixed NullPointerException in the Game class
  src/main/java/com/toptrumps/cli/TopTrumpsCLIApp.java
  src/main/java/com/toptrumps/core/DeckParser.java
  src/main/java/com/toptrumps/core/Game.java
Labels: enhancement

#19 Feature/deal cards
  src/main/java/com/toptrumps/cli/CommandLineUI.java
  src/main/java/com/toptrumps/cli/TopTrumpsCLIApp.java
  src/main/java/com/toptrumps/core/Dealer.java
  src/main/java/com/toptrumps/core/DeckParser.java
  src/main/java/com/toptrumps/core/Game.java
  src/main/java/com/toptrumps/core/Player.java
Labels: enhancement

#20 Added database connection functionality
  src/main/java/com/toptrumps/db/ConnectionFactory.java
Labels: enhancement

#18 Feature/show top card
  src/main/java/com/toptrumps/online/resources/GameWebPagesResource.java
  src/main/java/com/toptrumps/online/views/GameScreenView.java
  src/main/resources/assets/images/card_name.png
  src/main/resources/com/toptrumps/online/scripts/card.js
  src/main/resources/com/toptrumps/online/scripts/game.js
  src/main/resources/com/toptrumps/online/scripts/message.js
  src/main/resources/com/toptrumps/online/scripts/player.js
  src/main/resources/com/toptrumps/online/styles/game-screen.css
  src/main/resources/com/toptrumps/online/views/_parts/ai-player.ftl
  src/main/resources/com/toptrumps/online/views/_parts/card.ftl
  src/main/resources/com/toptrumps/online/views/_parts/footer.ftl
  src/main/resources/com/toptrumps/online/views/_parts/opponents.ftl
Labels: enhancement

#22 Feature/user select attribute
  src/main/java/com/toptrumps/cli/CommandLineUI.java
  src/main/java/com/toptrumps/core/Card.java
  src/main/java/com/toptrumps/core/Game.java
  src/main/java/com/toptrumps/core/Player.java
Labels: enhancement

#24 Added class that will control persistent game data in db.
  src/main/java/com/toptrumps/db/ConnectionFactory.java
  src/main/java/com/toptrumps/db/PersistentDataDAO.java
Labels: enhancement

#27 Add method to get player id
  src/main/java/com/toptrumps/online/api/TopTrumpsRESTAPI.java
  src/main/resources/com/toptrumps/online/scripts/game.js
Labels: enhancement

#28 Add category selection if a human player is active
  src/main/resources/com/toptrumps/online/scripts/card.js
  src/main/resources/com/toptrumps/online/scripts/game.js
  src/main/resources/com/toptrumps/online/scripts/message.js
  src/main/resources/com/toptrumps/online/scripts/player.js
  src/main/resources/com/toptrumps/online/styles/game-screen.css
Labels: enhancement

#29 Add AI player category selection workflow
  src/main/java/com/toptrumps/online/api/TopTrumpsRESTAPI.java
  src/main/resources/com/toptrumps/online/scripts/anime.min.js
  src/main/resources/com/toptrumps/online/scripts/card.js
  src/main/resources/com/toptrumps/online/scripts/countdown.js
  src/main/resources/com/toptrumps/online/scripts/game.js
  src/main/resources/com/toptrumps/online/styles/game-screen.css
  src/main/resources/com/toptrumps/online/views/GameScreen.ftl
  src/main/resources/com/toptrumps/online/views/_parts/footer.ftl
Labels: enhancement

#30 Show opponents cards after category is chosen
  src/main/java/com/toptrumps/online/api/TopTrumpsRESTAPI.java
  src/main/resources/com/toptrumps/online/scripts/card.js
  src/main/resources/com/toptrumps/online/scripts/game.js
  src/main/resources/com/toptrumps/online/scripts/player.js
  src/main/resources/com/toptrumps/online/views/GameScreen.ftl
  src/main/resources/com/toptrumps/online/views/_parts/card.ftl
Labels: enhancement

#31 Show card count for every player
  src/main/java/com/toptrumps/online/api/TopTrumpsRESTAPI.java
  src/main/resources/com/toptrumps/online/scripts/card.js
  src/main/resources/com/toptrumps/online/scripts/game.js
  src/main/resources/com/toptrumps/online/scripts/player.js
  src/main/resources/com/toptrumps/online/views/_parts/ai-player.ftl
  src/main/resources/com/toptrumps/online/views/_parts/card.ftl
  src/main/resources/com/toptrumps/online/views/_parts/human-player.ftl
Labels: enhancement

#32 Implement core game logic
  src/main/java/com/toptrumps/TopTrumps.java
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/cli/CommandLineUI.java
  src/main/java/com/toptrumps/cli/CommandLineView.java
  src/main/java/com/toptrumps/cli/TopTrumpsCLIApp.java
  src/main/java/com/toptrumps/core/AIPlayer.java
  src/main/java/com/toptrumps/core/Attribute.java
  src/main/java/com/toptrumps/core/Card.java
  src/main/java/com/toptrumps/core/Dealer.java
  src/main/java/com/toptrumps/core/DeckParser.java
  src/main/java/com/toptrumps/core/Game.java
  src/main/java/com/toptrumps/core/Player.java
  src/main/java/com/toptrumps/core/card/Attribute.java
  src/main/java/com/toptrumps/core/card/Card.java
  src/main/java/com/toptrumps/core/card/Dealer.java
  src/main/java/com/toptrumps/core/card/DeckParser.java
  src/main/java/com/toptrumps/core/engine/Game.java
  src/main/java/com/toptrumps/core/engine/GameEventListener.java
  src/main/java/com/toptrumps/core/engine/RoundOutcome.java
  src/main/java/com/toptrumps/core/player/AIPlayer.java
  src/main/java/com/toptrumps/core/player/IncompatibleComparisonException.java
  src/main/java/com/toptrumps/core/player/NoCardException.java
  src/main/java/com/toptrumps/core/player/NoSelectionException.java
  src/main/java/com/toptrumps/core/player/Player.java
  src/main/java/com/toptrumps/core/utils/ResourceLoader.java
  src/main/java/com/toptrumps/online/TopTrumpsOnlineApp.java
  src/main/java/com/toptrumps/online/resources/GameWebPagesResource.java
  src/main/java/com/toptrumps/online/views/GameScreenView.java
  src/main/resources/assets/banners/welcome.txt
Labels: enhancement

#33 Show game round outcome
  src/main/java/com/toptrumps/online/api/TopTrumpsRESTAPI.java
  src/main/resources/com/toptrumps/online/scripts/card.js
  src/main/resources/com/toptrumps/online/scripts/game.js
  src/main/resources/com/toptrumps/online/scripts/modal.js
  src/main/resources/com/toptrumps/online/scripts/player.js
  src/main/resources/com/toptrumps/online/styles/game-screen.css
  src/main/resources/com/toptrumps/online/views/GameScreen.ftl
  src/main/resources/com/toptrumps/online/views/_parts/footer.ftl
  src/main/resources/com/toptrumps/online/views/_parts/modal.ftl
Labels: enhancement

#34 Feature/online common pile count
  src/main/java/com/toptrumps/online/api/TopTrumpsRESTAPI.java
  src/main/resources/com/toptrumps/online/scripts/game.js
  src/main/resources/com/toptrumps/online/styles/game-screen.css
  src/main/resources/com/toptrumps/online/views/_parts/game-status.ftl
Labels: enhancement

#35 Feature/round results
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/core/engine/Game.java
  src/main/java/com/toptrumps/core/engine/RoundOutcome.java
Labels: enhancement

#42 Feature/restart game
  src/main/java/com/toptrumps/cli/CommandLineController.java
Labels: enhancement

#38 Added a statistics bean to objectify stats drawn from db.
  src/main/java/com/toptrumps/db/PersistentDataDAO.java
  src/main/java/com/toptrumps/db/Statistics.java
Labels: enhancement

#45 Make core game engine stateless and integrate with the online application
  TopTrumps.json
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/cli/TopTrumpsCLIApp.java
  src/main/java/com/toptrumps/core/card/Attribute.java
  src/main/java/com/toptrumps/core/card/Card.java
  src/main/java/com/toptrumps/core/card/Dealer.java
  src/main/java/com/toptrumps/core/engine/Game.java
  src/main/java/com/toptrumps/core/engine/GameEventListener.java
  src/main/java/com/toptrumps/core/engine/RoundOutcome.java
  src/main/java/com/toptrumps/core/player/AIPlayer.java
  src/main/java/com/toptrumps/core/player/Player.java
  src/main/java/com/toptrumps/online/api/TopTrumpsRESTAPI.java
  src/main/java/com/toptrumps/online/api/request/GamePreferences.java
  src/main/java/com/toptrumps/online/api/request/HumanPlayerMove.java
  src/main/java/com/toptrumps/online/api/request/PlayerMove.java
  src/main/java/com/toptrumps/online/api/request/PlayerState.java
  src/main/java/com/toptrumps/online/api/response/InitialGameState.java
  src/main/java/com/toptrumps/online/api/response/Outcome.java
  src/main/java/com/toptrumps/online/api/response/Winner.java
Labels: enhancement

#46 Fix some merge conflicts and mappings
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/online/api/TopTrumpsRESTAPI.java
Labels: bug

#48 Bugfix/winner incorrectly removed
  src/main/java/com/toptrumps/core/engine/Game.java
Labels: bug

#52 Feature/cli view
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/cli/CommandLineView.java
Labels: enhancement

#54 Feature/show winning card
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/cli/CommandLineView.java
Labels: enhancement

#59 Update README.md
  README.md
Labels: documentation

#62 Feature/game playability
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/cli/CommandLineView.java
Labels: enhancement

#64 Fix selected AIPlayer mapping
  src/main/java/com/toptrumps/online/api/TopTrumpsRESTAPI.java
  src/main/java/com/toptrumps/online/api/request/PlayerMove.java
Labels: bug

#66 Feature/card appearance
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/cli/CommandLineView.java
Labels: enhancement

#67 Gather game state from both Apps and persist it through core Game model
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/core/engine/Game.java
  src/main/java/com/toptrumps/core/statistics/GameStateCollector.java
  src/main/java/com/toptrumps/core/utils/MapUtils.java
  src/main/java/com/toptrumps/db/IndividualGameDAO.java
  src/main/java/com/toptrumps/db/IndividualGameDAOImpl.java
  src/main/java/com/toptrumps/online/api/TopTrumpsRESTAPI.java
  src/main/java/com/toptrumps/online/api/request/FinalGameState.java
  src/main/java/com/toptrumps/online/api/request/PlayerState.java
Labels: enhancement

#65 Improve AI Player highest attribute selection
  src/main/java/com/toptrumps/core/card/Card.java
  src/main/java/com/toptrumps/core/engine/Game.java
  src/main/java/com/toptrumps/core/utils/RandomGenerator.java
Labels: enhancement

#68 Refactored database and implementation.
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/core/engine/Game.java
  src/main/java/com/toptrumps/db/GameDAO.java
  src/main/java/com/toptrumps/db/GameDAOImpl.java
  src/main/java/com/toptrumps/db/IndividualGameDAO.java
  src/main/java/com/toptrumps/db/IndividualGameDAOImpl.java
  src/main/java/com/toptrumps/db/PerformanceDAOImpl.java
  src/main/java/com/toptrumps/db/PersistentDataDAO.java
  src/main/java/com/toptrumps/db/PersistentDataDAOImpl.java
  src/main/java/com/toptrumps/db/RoundWinnersDAO.java
  src/main/java/com/toptrumps/db/RoundWinnersDAOImpl.java
  src/main/java/com/toptrumps/db/Statistics.java
Labels: enhancement

#69 Create statistics GET operation to retrieve overall statistics content
  src/main/java/com/toptrumps/db/Statistics.java
  src/main/java/com/toptrumps/online/api/TopTrumpsRESTAPI.java
  src/main/java/com/toptrumps/online/api/response/StatisticsContent.java
Labels: enhancement

#70 Statistics && Add visual changes to the game interface
  src/main/resources/assets/images/icon_close.svg
  src/main/resources/assets/images/icon_crown.png
  src/main/resources/assets/images/icon_swords.png
  src/main/resources/assets/images/statistics_page_bg.jpg
  src/main/resources/com/toptrumps/online/scripts/game.js
  src/main/resources/com/toptrumps/online/scripts/helpers/dom.js
  src/main/resources/com/toptrumps/online/scripts/helpers/stats.js
  src/main/resources/com/toptrumps/online/scripts/plugins/message.js
  src/main/resources/com/toptrumps/online/scripts/plugins/modal.js
  src/main/resources/com/toptrumps/online/scripts/selection.js
  src/main/resources/com/toptrumps/online/styles/game-screen.css
  src/main/resources/com/toptrumps/online/styles/global.css
  src/main/resources/com/toptrumps/online/styles/stats-screen.css
  src/main/resources/com/toptrumps/online/views/GameScreen.ftl
  src/main/resources/com/toptrumps/online/views/SelectionScreen.ftl
  src/main/resources/com/toptrumps/online/views/Statistics.ftl
  src/main/resources/com/toptrumps/online/views/_parts/ActionPanel.ftl
  src/main/resources/com/toptrumps/online/views/_parts/GameStatus.ftl
  src/main/resources/com/toptrumps/online/views/_parts/Header.ftl
  src/main/resources/com/toptrumps/online/views/_parts/HumanPlayer.ftl
  src/main/resources/com/toptrumps/online/views/_parts/Modal.ftl
  src/main/resources/com/toptrumps/online/views/_parts/Template.ftl
Labels: enhancement

#72 Create a "TEST MODE"
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/cli/CommandLineView.java
  src/main/java/com/toptrumps/cli/PrintOptions.java
Labels: enhancement

#71 Fixed typo that broke the database.
  src/main/java/com/toptrumps/db/GameDAOImpl.java
Labels: bug

#73 Logger fix and showing stats
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/cli/CommandLineView.java
  src/main/java/com/toptrumps/cli/Logger.java
  src/main/java/com/toptrumps/core/card/Card.java
Labels: enhancement

#74 Quit option
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/cli/CommandLineView.java
Labels: enhancement

#76 Polish CommandLine start up logic
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/cli/GameOption.java
Labels: enhancement

#75 Added round wins display at end of game
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/cli/CommandLineView.java
Labels: enhancement

#78 Polish CommandLineController and add documentation
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/cli/TopTrumpsCLIApp.java
  src/main/java/com/toptrumps/core/engine/GameEngine.java
  src/main/java/com/toptrumps/online/api/TopTrumpsRESTAPI.java
Labels: enhancement

#80 Polish the Core Game Engine and add documentation
  src/main/java/com/toptrumps/core/engine/GameEngine.java
Labels: documentation

#81 Adds documentation to the Dealer and DeckParser classes
  src/main/java/com/toptrumps/core/card/Attribute.java
  src/main/java/com/toptrumps/core/card/Card.java
  src/main/java/com/toptrumps/core/card/Dealer.java
  src/main/java/com/toptrumps/core/card/DeckParser.java
  src/main/java/com/toptrumps/core/engine/GameEngine.java
  src/main/java/com/toptrumps/core/player/AIPlayer.java
  src/main/java/com/toptrumps/core/player/IncompatibleComparisonException.java
  src/main/java/com/toptrumps/core/statistics/GameStateCollector.java
  src/main/java/com/toptrumps/core/utils/RandomGenerator.java
Labels: documentation

#82 Feature/print auto rounds
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/cli/CommandLineView.java
  src/main/java/com/toptrumps/cli/PrintOptions.java
Labels: enhancement

#85 Loads deckFile name from TopTrumps.json
  src/main/java/com/toptrumps/TopTrumps.java
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/core/utils/ResourceLoader.java
  src/main/java/com/toptrumps/online/configuration/SimpleTopTrumpsConfig.java
Labels: enhancement

#84 Core unit tests
  pom.xml
  src/main/java/com/toptrumps/core/card/Dealer.java
  src/main/java/com/toptrumps/core/engine/GameEngine.java
  src/test/java/com/toptrumps/TopTrumpsTest.java
  src/test/java/com/toptrumps/core/card/DealerTest.java
  src/test/java/com/toptrumps/core/engine/CoreEngineTest.java
Labels: enhancement

#86 Enforce round cards to be shuffled before collected
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/core/card/Dealer.java
  src/main/java/com/toptrumps/core/engine/GameEngine.java
  src/test/java/com/toptrumps/core/engine/GameEngineTest.java
Labels: enhancement

#90 Code clean up | EPISODE I
  src/main/java/com/toptrumps/cli/Logger.java
  src/main/java/com/toptrumps/core/card/Card.java
  src/main/java/com/toptrumps/core/engine/GameEngine.java
  src/main/java/com/toptrumps/core/player/NoSelectionException.java
  src/main/java/com/toptrumps/core/player/Player.java
  src/main/java/com/toptrumps/online/api/TopTrumpsRESTAPI.java
  src/main/java/com/toptrumps/online/api/request/PlayerMove.java
Labels: enhancement

#91 Fix for bug that breaks card management
  src/main/java/com/toptrumps/online/resources/GameWebPagesResource.java
  src/main/java/com/toptrumps/online/views/GameScreenView.java
  src/main/resources/assets/images/favicon/favicon.ico
  src/main/resources/com/toptrumps/online/scripts/game.js
  src/main/resources/com/toptrumps/online/scripts/helpers/dom.js
  src/main/resources/com/toptrumps/online/scripts/helpers/network.js
  src/main/resources/com/toptrumps/online/styles/game-screen.css
Labels: bug

#92 Code clean up | EPISODE 2
  src/main/java/com/toptrumps/cli/CommandLineController.java
  src/main/java/com/toptrumps/cli/CommandLineView.java
  src/main/java/com/toptrumps/cli/PrintOptions.java
  src/main/java/com/toptrumps/cli/TopTrumpsCLIApp.java
Labels: enhancement

#94 Code clean up | EPISODE 3
  src/test/java/com/toptrumps/TopTrumpsTest.java
Labels: enhancement

#93 Multiple visual improvements
  src/main/java/com/toptrumps/online/TopTrumpsOnlineApp.java
  src/main/resources/com/toptrumps/online/scripts/game.js
  src/main/resources/com/toptrumps/online/scripts/helpers/dom.js
  src/main/resources/com/toptrumps/online/scripts/helpers/network.js
  src/main/resources/com/toptrumps/online/scripts/helpers/stats.js
  src/main/resources/com/toptrumps/online/scripts/models/player.js
  src/main/resources/com/toptrumps/online/scripts/plugins/modal.js
  src/main/resources/com/toptrumps/online/styles/game-screen.css
Labels: enhancement

#88 Cleaned up retrieval of all previous game data.
  TopTrumps.log.lck
  src/main/java/com/toptrumps/db/FullStats.java
  src/main/java/com/toptrumps/db/PlayersDAOImpl.java
  src/main/java/com/toptrumps/db/PlayersList.java
  src/main/java/com/toptrumps/db/Statistics.java
  src/main/java/com/toptrumps/online/api/response/StatisticsContent.java
Labels: enhancement

#95 Code comments and reorganization
  src/main/resources/com/toptrumps/online/scripts/GameController.js
  src/main/resources/com/toptrumps/online/scripts/SelectionController.js
  src/main/resources/com/toptrumps/online/scripts/StatisticsController.js
  src/main/resources/com/toptrumps/online/scripts/config/settings.js
  src/main/resources/com/toptrumps/online/scripts/game.js
  src/main/resources/com/toptrumps/online/scripts/helpers/logger.js
  src/main/resources/com/toptrumps/online/scripts/helpers/network.js
  src/main/resources/com/toptrumps/online/scripts/models/GameModel.js
  src/main/resources/com/toptrumps/online/scripts/models/StatsModel.js
  src/main/resources/com/toptrumps/online/scripts/models/player.js
  src/main/resources/com/toptrumps/online/scripts/plugins/countdown.js
  src/main/resources/com/toptrumps/online/scripts/plugins/input-number.js
  src/main/resources/com/toptrumps/online/scripts/plugins/message.js
  src/main/resources/com/toptrumps/online/scripts/plugins/modal.js
  src/main/resources/com/toptrumps/online/scripts/plugins/screen.js
  src/main/resources/com/toptrumps/online/scripts/selection.js
  src/main/resources/com/toptrumps/online/scripts/views/GameView.js
  src/main/resources/com/toptrumps/online/scripts/views/SelectionView.js
  src/main/resources/com/toptrumps/online/scripts/views/StatisticsView.js
  src/main/resources/com/toptrumps/online/views/GameScreen.ftl
  src/main/resources/com/toptrumps/online/views/SelectionScreen.ftl
  src/main/resources/com/toptrumps/online/views/Statistics.ftl
Labels: documentation, enhancement

#96 Change DB from yacata to AWS
  src/main/java/com/toptrumps/db/ConnectionFactory.java
Labels: enhancement

#97 Tweak online dynamics and add loader for requests
  src/main/resources/com/toptrumps/online/scripts/GameController.js
  src/main/resources/com/toptrumps/online/scripts/StatisticsController.js
  src/main/resources/com/toptrumps/online/scripts/plugins/loader.js
  src/main/resources/com/toptrumps/online/scripts/views/GameView.js
  src/main/resources/com/toptrumps/online/scripts/views/StatisticsView.js
  src/main/resources/com/toptrumps/online/styles/game-screen.css
  src/main/resources/com/toptrumps/online/styles/global.css
  src/main/resources/com/toptrumps/online/views/GameScreen.ftl
  src/main/resources/com/toptrumps/online/views/Statistics.ftl
Labels: enhancement

#99 Image optimization + smallest tweaks
  src/main/resources/assets/images/ai_player_card_back.png
  src/main/resources/assets/images/card_name.png
  src/main/resources/assets/images/cards/Arachas_Hatchling.png
  src/main/resources/assets/images/cards/Bloody_Baron.png
  src/main/resources/assets/images/cards/Ciri.png
  src/main/resources/assets/images/cards/Clan_Skirmisher.png
  src/main/resources/assets/images/cards/Commander_s_Horn.png
  src/main/resources/assets/images/cards/Dandelion.png
  src/main/resources/assets/images/cards/Default.png
  src/main/resources/assets/images/cards/Dol_Blathanna_Archer.png
  src/main/resources/assets/images/cards/Dwarf_Adventurer.png
  src/main/resources/assets/images/cards/Earth_Elemental.png
  src/main/resources/assets/images/cards/Emhyr_Var_Emreis.png
  src/main/resources/assets/images/cards/Eredin.png
  src/main/resources/assets/images/cards/Geralt_From_Rivia.png
  src/main/resources/assets/images/cards/Imlerith.png
  src/main/resources/assets/images/cards/Infantry.png
  src/main/resources/assets/images/cards/Kaedweni_Sergeant.png
  src/main/resources/assets/images/cards/King_Foltest.png
  src/main/resources/assets/images/cards/King_Radovid_V.png
  src/main/resources/assets/images/cards/Lambert.png
  src/main/resources/assets/images/cards/Morvudd.png
  src/main/resources/assets/images/cards/Mutated_Hounds.png
  src/main/resources/assets/images/cards/Olgierd_Von_Everec.png
  src/main/resources/assets/images/cards/Philippa_Eilhart.png
  src/main/resources/assets/images/cards/Pirate.png
  src/main/resources/assets/images/cards/Priestess_of_Freya.png
  src/main/resources/assets/images/cards/Reconnaissance.png
  src/main/resources/assets/images/cards/Redanian_Elite.png
  src/main/resources/assets/images/cards/Regis.png
  src/main/resources/assets/images/cards/Revenant.png
  src/main/resources/assets/images/cards/Roach.png
  src/main/resources/assets/images/cards/Sigismund_Dijkstra.png
  src/main/resources/assets/images/cards/Temerian_Infantryman.png
  src/main/resources/assets/images/cards/Tormented_Mage.png
  src/main/resources/assets/images/cards/Triss_Merigold.png
  src/main/resources/assets/images/cards/Trollololo.png
  src/main/resources/assets/images/cards/Vernon_Roche.png
  src/main/resources/assets/images/cards/Vesemir.png
  src/main/resources/assets/images/cards/Warcrier.png
  src/main/resources/assets/images/cards/Woodland_Spirit.png
  src/main/resources/assets/images/cards/Yennefer.png
  src/main/resources/assets/images/cards/Zoltan.png
  src/main/resources/assets/images/game_page_bg.jpg
  src/main/resources/assets/images/human_player_card_back.png
  src/main/resources/assets/images/lost_player_card_back.png
  src/main/resources/assets/images/selection_page_bg.jpg
  src/main/resources/assets/images/statistics_page_bg.jpg
  src/main/resources/com/toptrumps/online/scripts/plugins/screen.js
  src/main/resources/com/toptrumps/online/styles/global.css
Labels: enhancement
